# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Николай\PycharmProjects\untitled1\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300,400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 50, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(150, 50, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 80, 241, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image downloader"))
        self.comboBox.setItemText(0, _translate("MainWindow", "01"))
        self.comboBox.setItemText(1, _translate("MainWindow", "02"))
        self.comboBox.setItemText(2, _translate("MainWindow", "03"))
        self.comboBox.setItemText(3, _translate("MainWindow", "04"))
        self.comboBox.setItemText(4, _translate("MainWindow", "05"))
        self.comboBox.setItemText(5, _translate("MainWindow", "05"))
        self.comboBox.setItemText(6, _translate("MainWindow", "07"))
        self.comboBox.setItemText(7, _translate("MainWindow", "08"))
        self.comboBox.setItemText(8, _translate("MainWindow", "09"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "2018"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2017"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "2016"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "2015"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "2014"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "2013"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "320x480"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "640x480"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "800x480"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "800x600"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "1024x768"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "1024x1024"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "1152x864"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "1280x720"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "1280x960"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "1280x1024"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "1366x768"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "1400x1050"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "1440x900"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "1600x1200"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "1680x1050"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "1680x1200"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "1920x1080"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "1920x1200"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "1920x1440"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "2560x1440"))
        self.pushButton.setText(_translate("MainWindow", "download"))

